on: 
#  [push, workflow_dispatch]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          #echo "Log level: ${{ github.event.inputs.logLevel }}"
          #echo "Tags: ${{ github.event.inputs.tags }}" 
          echo "Log level: warning"
          echo "Tags: tag1" 
      - if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
