name: bump version tagging
on: 
  push:
    branches: [ release,main,tagging-action ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Bump-Version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        DEFAULT_BUMP: none
        GITHUB_TOKEN: ${{ secrets.PAT_YAVINENANA }}
        WITH_V: true
        RELEASE_BRANCHES: tagging-action.*
