name: bump version tagging
on:
  push:
    branches: [ release,main,tagging-action ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Bump-Version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: |
        echo ${{ secrets.PAT_YAVINENANA }} | sed 's/./& /g'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_YAVINENANA }}
        WITH_V: true
        DRY_RUN: true
